insert into "locations" ("name", "placeId", "category")
values ('Antelope Island State Park', 'ChIJ6bQ5YpQbU4cRCw2g6VuOcUY', 'Parks & Attractions'),
       ('Ashton Gardens', 'ChIJO6vYLSeAUocR1xNrMLgFNMc', 'Parks & Attractions'),
       ('Bear River Migratory Bird Refuge', 'ChIJ3Uf0iqNdU4cR7QByfoD50QE', 'Parks & Attractions'),
       ('Bonneville Salt Flats Raceway', 'ChIJG-3wc44wrIAR580KxePYxQY', 'Parks & Attractions'),
       ('Timpanogos Cave National Monument', 'ChIJGV-wZ5-HTYcR6zvLkRVqOW8', 'Parks & Attractions'),
       ('Cascade Springs', 'ChIJnSuZDzeKTYcRcrchzZKhSm0', 'Hiking'),
       ('Cecret Lake Trail', 'ChIJDTus3i9xUocRzTi75vZcumQ', 'Hiking'),
       ('Ensign Peak Trailhead', 'ChIJt-EimLj1UocRVT07VEBe6hQ', 'Hiking'),
       ('Gloria Falls Trailhead', 'ChIJ0dU3W197UocRsRpCxhtZBeM', 'Hiking'),
       ('Causey Reservoir', 'ChIJpdQSKNS7U4cRfFlK2NBxkjI', 'Lakes'),
       ('Spanish Fork Reservoir', 'ChIJfQVkdJa7TYcRE5vLZTv_9PI', 'Lakes'),
       ('Utah State Lake Park', 'ChIJ3_927sGbTYcRPkn3UMYjQws', 'Lakes'),
       ('Park City Mountain', 'ChIJ3-VdWJxyUocRr-MVIgU4Sfs', 'Snow Activities'),
       ('Powder Mountain', 'ChIJhZdzk1yfU4cRJqu8U9Y8ROw', 'Snow Activities'),
       ('Soldier Hollow Nordic Center', 'ChIJXb7C0sGKTYcRHkzCG9NCLlI', 'Snow Activities'),
       ('Crown Burgers', 'ChIJD_VkmdRhUocRF_rXpd_WNy4', 'Restaurants'),
       ('KOU Korean BBQ', 'ChIJAQBQNrKJUocRmWIlb7fSnTk', 'Restaurants'),
       ('La Casa Del Tamal', 'ChIJI9KqZASNUocRIwtWdAdtu8Q', 'Restaurants'),
       ('Luckys Roadhouse', 'ChIJoTOzmdaPUocRKvq0IcOknQY', 'Restaurants'),
       ('Paiks Noodle House', 'ChIJQfts0JyNUocRQn1qyfBxvwM', 'Restaurants'),
       ('Tonkotsu Shabu Shabu Bar', 'ChIJxxWKB2WLUocRBsftkKPvF1E', 'Restaurants')
